# SETUP
baseurl = "/"
DefaultContentLanguage = "fi"
publishdir = "public"
canonifyUrls = "true"
disableKinds = ["RSS","taxonomy","taxonomyTerm"] # disable hugo's content that we don't need...

title = "Mainosnäyttö Särkisalmi Parikkala – Saimaanpixel.fi – Mainonnan ratkaisut" # page title -> see ./layouts/partials/head.html

googleAnalytics = "" # if needed...

[author]
    name = "Saimaanpixel"
    email = "myynti@saimaanpixel.fi"

[params]
    description = "Kuutostien paras valomainospaikka" # page description -> see ./layouts/partials/head.html
